Adding Data Loaders and required utils to use KITTI Tracking dataset
raviteja-konduru/OpenPCDet_Obj_tracking pull request #4
Opened 2020-11-12 09:51 UTC by raviteja-kvns

2020-11-13 01:09 UTC, Anirudh-Swaminathan requested changes

2020-11-13 01:09 UTC, Anirudh-Swaminathan commented on tools/cfgs/dataset_configs/kitti_tracking_dataset.yaml
> +DATASET: 'KittiDataset'
Change name to KittiTrackingDataset

2020-11-13 01:09 UTC, Anirudh-Swaminathan commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +# Generating train.txt file with the given sequences
Save ImageSets/train.txt to ImageSets/exp_001/train.txt also, to ensure that we record different configurations for each experiment. We could also write config.txt to document this fact.

This means that it is OK to overwrite train.txt without worrying about losing experimental details.

Another thing is to include command line arguments to specify the number of the experiment and the name of the folder to write to

2020-11-13 01:29 UTC, raviteja-kvns commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +selected_val_seq = ["0009", "0010"]
Take in as comma separated string as arguments

2020-11-13 01:29 UTC, raviteja-kvns commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +base_path = "../../../../data/kitti-odometry/"
Take in as argument

2020-11-13 01:29 UTC, raviteja-kvns commented on tools/cfgs/dataset_configs/kitti_tracking_dataset.yaml
> +    'train': [kitti_track_seq_infos_train.pkl],
Track with some experiment ID to prevent being overwritten

2020-11-13 01:29 UTC, raviteja-kvns commented on pcdet/datasets/kitti/kitti_tracking_seq_dataset.py
> +        self.sample_id_list = [x.strip().split(' ') for x in open(split_dir).readlines()] if split_dir.exists() else None # Will now have seq also
Add a comment: List of lists

2020-11-13 01:29 UTC, raviteja-kvns commented on pcdet/datasets/kitti/kitti_tracking_seq_dataset.py
> +        img_file = self.root_split_path / 'image_2' / seq / ('%s.png' % idx)
change image_2 -> image_02

2020-11-13 01:29 UTC, raviteja-kvns commented on pcdet/datasets/kitti/kitti_tracking_seq_dataset.py
> +        label_file = self.root_split_path / 'label_02' / ('%s.txt' % idx)
Use seq instead of idx

2020-11-17 02:41 UTC, Anirudh-Swaminathan approved these changes

2020-11-18 10:40 UTC, raviteja-kvns commented on tools/cfgs/dataset_configs/kitti_tracking_dataset.yaml
> +DATASET: 'KittiDataset'
Done

2020-11-18 10:42 UTC, raviteja-kvns commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +# Generating train.txt file with the given sequences
Done

2020-11-18 10:43 UTC, raviteja-kvns commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +selected_val_seq = ["0009", "0010"]
Done

2020-11-18 10:43 UTC, raviteja-kvns commented on tools/data_utils/ImageSetGenerators/kitti-odometry/generate_for_selected_seq.py
> +base_path = "../../../../data/kitti-odometry/"
Done

2020-11-18 10:43 UTC, raviteja-kvns commented on tools/cfgs/dataset_configs/kitti_tracking_dataset.yaml
> +    'train': [kitti_track_seq_infos_train.pkl],
Done. But could do it only in a crude way.

2020-11-18 10:45 UTC, raviteja-kvns commented on pcdet/datasets/kitti/kitti_tracking_seq_dataset.py
> +        self.sample_id_list = [x.strip().split(' ') for x in open(split_dir).readlines()] if split_dir.exists() else None # Will now have seq also
Done

2020-11-18 10:45 UTC, raviteja-kvns commented on pcdet/datasets/kitti/kitti_tracking_seq_dataset.py
> +        img_file = self.root_split_path / 'image_2' / seq / ('%s.png' % idx)
Done

2020-11-22 21:26 UTC, merged